### ISSUE TITLE
BoM information

### ISSUE THREAD

**Issue by ZiadJ** [Nate711/StanfordDoggoProject#1]
Is there any information available on the costs involved in building this little machine? I heard from the video that it wouldn't be more than $3k which is well above what the average tinkerer can afford. I'm not sure what exactly would justify the costs of the current setup but I'm hoping that having some information about it would help figure out how to lower the costs eventually for less demanding environments.

**Comment by CrazyAZ** [comment]
We have a [BOM spreadsheet](https://docs.google.com/spreadsheets/d/1MQRoZCfsMdJhHQ-ht6YvhzNvye6xDXO8vhWQql2HtlI/edit#gid=726381752) which gives a break down of the cost.  And I'd be happy to give a few thoughts on how it could be made cheaper.

The two most expensive items are the motors and motor controllers, which would be hard to replace, but after that come the custom parts.  We calculated our cost assuming that these custom parts would be outsourced, allowing Doggo to be built by anyone with common hand tools.  However, if you have access to a 3D printer or waterjet cutter you can produce these parts for cheaper than if you pay another service to make them for you.

With that said, an SLS 3D printer and waterjet cutter are likely not accessible to the average tinkerer either.  So the following are some possible ways you could get around needing these expensive pieces of equipment, but I cannot guarantee how well they will actually work.

First, the pulleys could be printed with a more standard and cheaper 3D printer.  The worry is that the tolerances may not be very good and the timing belts may not fit as well.

You could also try replacing the waterjet parts with laser cut parts.  This would require a pretty significant change in the materials these parts are made of since carbon fiber and aluminum can't be laser cut, and replacing these materials will result in significantly weaker parts.  The only laser cuttable material I know of that is even close to these in durability is delrin, which is also pretty expensive and may or may not actually save you money.  There are certainly cheaper materials you could try, but your parts may break while operating the robot.

I hope this helps.  Let me know if you have any more questions.
