### ISSUE TITLE
Error when open the fusion model version2

### ISSUE THREAD

**Issue by CS4Liu** [Nate711/StanfordDoggoProject#29]
Hello,I try to use Autodesk Fusion 360 to open the fusion model version2 for more details of Doggo.But when I upload the 'Full Doggo Assembly.f3z' in the Autodesk Fusion 360 the error comes:
 
![image](https://user-images.githubusercontent.com/25763834/61541761-cfc07100-aa72-11e9-85c2-bf622fbbb832.png)
Do know how can I solve this problem？
Thanks!

**Comment by CrazyAZ** [comment]
I see that you have closed this issue. Did you find a solution to it? Someone else is having the same problem, but I cannot find anything wrong in the CAD.

**Comment by CS4Liu** [comment]
I didn't find solution to it. There still error when uploading the version2.Instead, I just download the Inventor 2018 version of the model, then open the '.ipt' file using Autodesk fusion 360 software.
then it works.

And I think there is some wrong with the model v172  in https://a360.co/2CPZoto because it has became like this now:  


------------------ 原始邮件 ------------------
发件人: "Aaron Schultz"<notifications@github.com>;
发送时间: 2019年7月31日(星期三) 中午12:43
收件人: "Nate711/StanfordDoggoProject"<StanfordDoggoProject@noreply.github.com>;
抄送: "csliu"<773849295@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [Nate711/StanfordDoggoProject] Error when open the fusion modelversion2 (#29)




I see that you have closed this issue. Did you find a solution to it? Someone else is having the same problem, but I cannot find anything wrong in the CAD.

**Comment by maxsu** [comment]
@CS4Liu, @CrazyAZ - this is still an issue with the project. It's caused by corrupted Simstudies: See the last post of [#34](https://github.com/Nate711/StanfordDoggoProject/issues/34), as well as this fusion 360 [support thread](https://forums.autodesk.com/t5/fusion-360-support/stanford-doggo-public-link-upload-issue/m-p/9006809/highlight/true) for a repaired version of the file.

I'd like to get this issue resolved. Can I join the CAD team?
