### ISSUE TITLE
Motor Spacer

### ISSUE THREAD

**Issue by danbo2** [Nate711/StanfordDoggoProject#43]
Can someone tell me whether the Motor Spacer is in purchasing list.
![Screenshot (22)](https://user-images.githubusercontent.com/16380245/67602572-e26ad600-f744-11e9-89b4-8cad113f7238.png)

**Comment by Kevinskwk** [comment]
Hi there! I also didn't find this spacer in the purchasing list. Alternatively, we laser cut the spacer out of acrylic sheet when we made it. I don't actually recommend using acrylic since this part seems to be load-bearing and this is only our temporary solution. I think you should consider using stronger material if possible. Cheers!

**Comment by danbo2** [comment]
@Kevinskwk  Thanks for your help. I have downloaded the fusion 3D model and extracted this part for 3D printing.
