### ISSUE TITLE
Regarding current flow amperage of each motor

### ISSUE THREAD

**Issue by HelloPlanet** [Nate711/StanfordDoggoProject#9]
Hi Nate and team, 

I'm trying to build a doggo here, while checking ODrive part, I found that the battery have a peak working current of 75A, each battery supplies four motors. But banana connectors from ODrive to motor is 3.5mm which allow 30A continuous current. This is a bit unclear to follow.

Do we have any test results on how much cuurent each motor draw from the drive? Thanks.

Edit:
Also, I found it hard to figure out how the battery power is distributed to PDB and ODrive boards. 
As I have experience working with quadcopter, I can think of some schemes that work, but still, i'm curious how you guys will distribute battery power.

My idea: 
Battery#1 
.....|
Contactor  
.....|-PDB
.....|--ODrive#1
.....|--ODrive#2

Battery#2 
.....|--ODrive#3
.....|--ODrive#4

Is this correct?

**Comment by Nate711** [comment]
Hi there. Thanks for your diligence! The peak current drawn by the motors is around 40A and the average is around 5A so the 30A continuous limit on the bullet connectors is completely fine. 

For the electronics wiring, please reference the README for this project which includes a little diagram on how everything goes. Basically the two batteries are connected in parallel to the PDB, which then powers the four ODrives. It's very much like a quadcopter setup except that we have two batteries in parallel going to the PDB instead of just one.

**Comment by HelloPlanet** [comment]
Thanks Nate, that explained everything.

**Comment by 790947648** [comment]
nice

**Comment by 790947648** [comment]
Looking forward to seeing your second edition of Doggo
